/**
 * Sample survey answers demonstrating various product improvement requests
 */
export const sampleAnswers = [
  { customer_id: 'cust_001', answer_text: 'Better mobile app with offline mode for field work' },
  { customer_id: 'cust_002', answer_text: 'Faster loading times and smoother animations throughout' },
  { customer_id: 'cust_003', answer_text: 'More customization options for the dashboard layout' },
  { customer_id: 'cust_004', answer_text: 'Dark mode support would be great for late night usage' },
  { customer_id: 'cust_005', answer_text: 'Better API documentation with more code examples' },
  { customer_id: 'cust_006', answer_text: 'Improved search functionality across all modules' },
  { customer_id: 'cust_007', answer_text: 'More integrations with third-party tools like Slack and Teams' },
  { customer_id: 'cust_008', answer_text: 'Keyboard shortcuts for power users to navigate faster' },
  { customer_id: 'cust_009', answer_text: 'Better error messages and debugging tools for developers' },
  { customer_id: 'cust_010', answer_text: 'Multi-language support, especially German and French' },
  { customer_id: 'cust_011', answer_text: 'Export options to Excel and PDF with better formatting' },
  { customer_id: 'cust_012', answer_text: 'Real-time collaboration features like Google Docs' },
  { customer_id: 'cust_013', answer_text: 'More chart types and visualization options for data' },
  { customer_id: 'cust_014', answer_text: 'Bulk operations for editing multiple items at once' },
  { customer_id: 'cust_015', answer_text: 'Better mobile responsiveness on tablets' },
  { customer_id: 'cust_016', answer_text: 'Improved notification system with better filtering' },
  { customer_id: 'cust_017', answer_text: 'Role-based permissions with more granular control' },
  { customer_id: 'cust_018', answer_text: 'Undo/redo functionality for all actions' },
  { customer_id: 'cust_019', answer_text: 'Better onboarding tutorial for new users' },
  { customer_id: 'cust_020', answer_text: 'Automated backup and restore features' },
  { customer_id: 'cust_021', answer_text: 'Integration with popular calendar apps' },
  { customer_id: 'cust_022', answer_text: 'Customizable email templates for notifications' },
  { customer_id: 'cust_023', answer_text: 'Better performance on large datasets (10k+ rows)' },
  { customer_id: 'cust_024', answer_text: 'Version history and audit trail for all changes' },
  { customer_id: 'cust_025', answer_text: 'More flexible filtering and sorting options' },
  { customer_id: 'cust_026', answer_text: 'Support for custom fields and metadata' },
  { customer_id: 'cust_027', answer_text: 'Better mobile app with push notifications' },
  { customer_id: 'cust_028', answer_text: 'Improved import/export functionality with validation' },
  { customer_id: 'cust_029', answer_text: 'More accessibility features for screen readers' },
  { customer_id: 'cust_030', answer_text: 'Better caching to reduce server load' },
  { customer_id: 'cust_031', answer_text: 'Drag and drop functionality for easier organization' },
  { customer_id: 'cust_032', answer_text: 'Advanced search with regex and boolean operators' },
  { customer_id: 'cust_033', answer_text: 'Scheduled reports and automated exports' },
  { customer_id: 'cust_034', answer_text: 'Better documentation with video tutorials' },
  { customer_id: 'cust_035', answer_text: 'Customizable dashboard widgets' },
  { customer_id: 'cust_036', answer_text: 'Better error recovery and auto-save features' },
  { customer_id: 'cust_037', answer_text: 'More theme options beyond dark and light mode' },
  { customer_id: 'cust_038', answer_text: 'Integration with project management tools like Jira' },
  { customer_id: 'cust_039', answer_text: 'Better support for touch gestures on mobile devices' },
  { customer_id: 'cust_040', answer_text: 'Improved data validation and error prevention' },
  { customer_id: 'cust_041', answer_text: 'More detailed analytics and reporting features' },
  { customer_id: 'cust_042', answer_text: 'Better handling of concurrent edits by multiple users' },
  { customer_id: 'cust_043', answer_text: 'Improved table view with frozen headers and columns' },
  { customer_id: 'cust_044', answer_text: 'Better print layouts for documentation' },
  { customer_id: 'cust_045', answer_text: 'More keyboard navigation options throughout the app' },
  { customer_id: 'cust_046', answer_text: 'Better handling of large file uploads with progress indicators' },
  { customer_id: 'cust_047', answer_text: 'Improved help system with context-sensitive tips' },
  { customer_id: 'cust_048', answer_text: 'More flexible date and time formatting options' },
  { customer_id: 'cust_049', answer_text: 'Better integration with SSO providers like Okta' },
  { customer_id: 'cust_050', answer_text: 'Overall very happy with the product, just minor UI polish needed' }
];
